### ISSUE TITLE
表單_表單標記必填欄位

### ISSUE THREAD

**Issue by KK-Huang86** [astrocamp/17th-WorkNet#198]
參考五倍的網站，表單必填以紅色 * 標示

![upload_23166160b22e243856fa076e013f0a2c](https://github.com/user-attachments/assets/cc7bb61f-8c0e-44b8-a66e-eeb1cdad2026)

**Comment by KK-Huang86** [comment]
但我們的表單基本上都是設定「必填」，這樣還有必要標示嗎

**Comment by kait-wu** [comment]
> 但我們的表單基本上都是設定「必填」，這樣還有必要標示嗎

感覺可以在使用者按下送出按鈕的時候跳提示之類的（？

**Comment by Gujiahan** [comment]
雖然 送出表單有提醒哪些必填,但還是加個提示哪些必填,不用等送出才知道...?
