### ISSUE TITLE
修改_userinfo_nickname如果沒有填寫,名字會是一個None

### ISSUE THREAD

**Issue by Gujiahan** [astrocamp/17th-WorkNet#217]
第三方登入之後雖然會判別有沒有填寫nickname來決定是否去首頁或是會員資訊
再被導去會員資訊之後還是能透過點擊首頁去做應徵的功能或是其他功能
如果提交應徵後,公司方收到履歷的名字會是一個None
<img width="864" alt="螢幕擷取畫面 2024-09-20 143444" src="https://github.com/user-attachments/assets/83cea24e-a130-44cb-985e-d008e5fca579">

**Comment by Ellen9543** [comment]
與第三方登入無關
只要是註冊完沒填會員資訊 nickname 是空的就會有這個問題
