### ISSUE TITLE
權限_公司的職缺

### ISSUE THREAD

**Issue by KK-Huang86** [astrocamp/17th-WorkNet#249]
公司登入後，點選職缺，可以看到該公司所有的職缺，

我們現在的網址為 /companies/ 公司id / jobs(例如：http://127.0.0.1:8000/companies/56/jobs)

然而，公司可以手動輸入 公司id進入別人的職缺（例如：http://127.0.0.1:8000/companies/57/jobs）

因此，需要擋權限（或者要把id拔掉？？）

**Comment by Ellen9543** [comment]
公司-職缺
非自己公司不能 [新增] 按鈕 & url
非自己公司不能 [編輯] 按鈕 (url有擋了)
非自己公司不能 [刪除] 按鈕 & url

/jobs => issues/157 有處理
/companies/1/jobs => 還沒處理
