### ISSUE TITLE
500 & 沒權限 頁面

### ISSUE THREAD

**Issue by kait-wu** [astrocamp/17th-WorkNet#254]

**Comment by Ellen9543** [comment]
![image](https://github.com/user-attachments/assets/8a1d3793-63a3-4636-a9c6-5c94373c6d7d)
![image](https://github.com/user-attachments/assets/39a7b9a8-aa11-48fb-af55-0b8a14e0c8ac)

**Comment by Ellen9543** [comment]
與 #260 一併調整 ( PR #261 )
