### ISSUE TITLE
通知系統_欄位(models)設計

### ISSUE THREAD

**Issue by KK-Huang86** [astrocamp/17th-WorkNet#33]
設計通知系統要有的欄位

| 欄位名稱 | 資料型態 | 描述 | 範例 |
| -------- | -------- | -------- | -------- |
| title  |  CharField | default="新訊息" |  |
|  message  |  CharField   |      |   |
| created_at |  DateTimeField |      |   |
|is_read  |  BooleanField  |    |   |
|user  |  ForeignKey  |    |   |

**Comment by Ellen9543** [comment]
新增 Notification
欄位: recipient、sender、title、message、created_at、read

先處理 Model & 公司新增職缺的時候有關注該公司的 user 要收到通知
 #149 處理
