### ISSUE TITLE
功能_評論區按讚/倒讚

### ISSUE THREAD

**Issue by kait-wu** [astrocamp/17th-WorkNet#41]
1. 按讚/倒讚
2. 收回讚/倒讚
3. 顯示按讚/倒讚的數量

**Comment by Ellen9543** [comment]
#### 調整 Post model 
+ 關聯 user_id
+ add field : like_cnt, dislike_cnt 

#### 新增 LikeLog model
+ post_id, user_id, created_at, like_type ( 1=讚 / -1=倒讚 )
