### ISSUE TITLE
修改_重複收藏的錯誤 改成按下收藏變成取消收藏的按鍵

### ISSUE THREAD

**Issue by Gujiahan** [astrocamp/17th-WorkNet#98]

**Comment by KK-Huang86** [comment]
https://github.com/astrocamp/17th-WorkNet/pull/119

看起來這個issues有發PR，但又被關掉，是還沒做完或者有其他考量呢（我原本想說要接手來做，但看到影片似乎是功能做完了）

**Comment by Gujiahan** [comment]
因為上次看到 ptt 有看到 按下收藏之後按鈕會轉換成取消,想說做完的話 那我就先把pr關掉了
